# Generated by Django 3.2.7 on 2021-09-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.EmailField(max_length=50),
        ),
    ]
