# Generated by Django 3.2.7 on 2021-09-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_auto_20210919_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.FloatField(blank=True)),
                ('usability', models.FloatField(blank=True)),
                ('content', models.FloatField(blank=True)),
            ],
        ),
    ]
