# Generated by Django 3.2.7 on 2021-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0004_auto_20210920_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
